#mkdocs.yml should live in the top level

site_name: UMass Amherst Experimental Linguistics
site_description: 'Joint Labs Documentation'
remote_branch: 'master' #`mkdocs gh-deploy` should push to master branch, so if you forget it should still go through

theme:
  name: 'material'
  #if we had a logo, we would theoretically be able to change it, not that i've had luck with this silly wug.svg
  palette:
    primary: 'teal'
    accent: 'deep purple'
  #any google fonts font! 

docs_dir: 'docs-md'

pages:
  - Home: index.md
  - Joint Labs:
      - Phonetics Lab: phon_info.md
      - Cognitive Science of Language Lab: csl_info.md
  - Guides:
      - Eyetracking: et_tutorials.md
      - Phonetics: phon_tutorials.md
      - Ibex Farm: ibex_guide.md
      - IRB: irb_guide.md
      - SONA: ling-sona.md
      - OSF: osf_guide.md
      - RAs: RA_guide.md
  - Resources: resources.md 

markdown_extensions:
  - admonition #enables note/warning boxes
  - toc:
      permalink: true #header permalinks on hover



